esphome:
  name: development
  friendly_name: development

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    advanced:
      minimum_chip_revision: "3.1"
      sram1_as_iram: true

api:

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

ota:
  platform: esphome

packages:
  directolor:
    url:  https://github.com/loucks1/Directolor-ESPHome
    ref: feature/nrf24-espidf-integration
    refresh: 1s
    files:
      - path: plumbing.yaml
      - path: directolor_cover.yaml
        vars:
          id: test_shade
          name: "Test Shade"
          radio_code: [0x06, 0x04, 0x05, 0x12]
          tilt_supported: true
          channel: 1
          movement_duration: 10s
          disable_favorite_support: true
          disable_program_support: true

button:
  - platform: restart
    name: "ESP Reboot"
    icon: mdi:power-cycle