# buttons.yaml - Simple package for two configurable buttons

substitutions:
  nrf24l01base_id: nrf24l01
  cover_id: directolor_shade
  cover_name: Upper Shades Right
  cover_movement_duration: 0s
  cover_channel: 3
  cover_tilt_supported: false
  cover_favorite_support: false
  cover_program_support: false
  
cover:
  - platform: directolor_cover
    base: ${nrf24l01base_id}
    id: $cover_id
    name: $cover_name
    radio_code:   #0x11, 0x11, 0xB9, 0x7B
      - 0x11
      - 0x11
      - 0xB9
      - 0x7B
    movement_duration: ${movement_duration}
    channel: ${cover_channel}
    tilt_supported: ${cover_tilt_supported}
