# buttons.yaml - Simple package for two configurable buttons

external_components:
  source: github://loucks1/Directolor-ESPHome@IssueWithFavoriteAndProgram
  refresh: 1s

substitutions:
  nrf24_ce_pin: 22
  nrf24_cs_pin: 21
  cover_id: directolor_shade
  cover_name: Upper Shades Right
  cover_movement_duration: 0s
  cover_channel: 3
  cover_tilt_supported: false
  cover_favorite_support: false
  cover_program_support: false

nrf24l01_base:
  id: nrf24l01
  ce_pin: ${nrf24_ce_pin}
  cs_pin: ${nrf24_cs_pin}
  
cover:
  - platform: directolor_cover
    base: nrf24l01
    id: $cover_id
    name: $cover_name
    radio_code:   #0x11, 0x11, 0xB9, 0x7B
      - 0x11
      - 0x11
      - 0xB9
      - 0x7B
    movement_duration: ${cover_movement_duration}
    channel: ${cover_channel}
    tilt_supported: ${cover_tilt_supported}
