substitutions:
  nrf24_ce_pin: GPIO22
  nrf24_cs_pin: GPIO21
  id: directolor_shade
  name: Directolor Shade
  movement_duration: 0s
  channel: 1
  tilt_supported: false
  disable_favorite_support: false
  disable_program_support: false
  radio_code: [0x06, 0x03, 0x05, 0x12]

external_components:
#  - source:
#      type: git
#      url: https://github.com/loucks1/nrf24_espidf
#      path: components
#    components: [ nrf24 ]
    #refresh: 0s 

  - source: 
      type: local
      path: ./components
    components: [ directolor_cover ]
     
cover:
  - platform: directolor_cover
    id: ${id}
    name: ${name}
    directolor_radio_id: ${radio_hub_id}
    radio_code: ${radio_code}
    movement_duration: ${movement_duration}
    channel: ${channel}
    tilt_supported: ${tilt_supported}

button:
  - platform: template
    id: "${id}_to_favorite"
    name: "${name} to favorite"
    icon: mdi:star 
    disabled_by_default: ${disable_favorite_support}
    on_press:
      then:
        - lambda: id(${id})->issue_shade_command(directolor_toFav);
  - platform: template
    id: "${id}_set_favorite"
    name: "${name} set favorite"
    icon: mdi:star-plus
    disabled_by_default: ${disable_favorite_support}
    on_press:
      then:
        - lambda: id(${id})->issue_shade_command(directolor_setFav);
  - platform: template
    id: "${id}_duplicate"
    name: "${name} Duplicate"
    icon: mdi:content-duplicate
    disabled_by_default: ${disable_program_support}
    on_press:
      then:
        - lambda: id(${id})->issue_shade_command(directolor_duplicate);
  - platform: template
    id: "${id}_join"
    name: "${name} Join"
    icon: mdi:plus
    disabled_by_default: ${disable_program_support}
    on_press:
      then:
        - lambda: id(${id})->issue_shade_command(directolor_join);
  - platform: template
    id: "${id}_remove"
    name: "${name} Remove"
    icon: mdi:selection-ellipse-remove
    disabled_by_default: ${disable_program_support}
    on_press:
      then:
        - lambda: id(${id})->issue_shade_command(directolor_remove);
