# plumbing.yaml
substitutions:
  # Default Pin Assignments
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
  cs_pin: GPIO21
  ce_pin: GPIO22
  payload_send_attempts: 3
  payload_send_repeats: 513

spi:
  - id: nrf24_spi
    clk_pin: ${clk_pin}
    mosi_pin: ${mosi_pin}
    miso_pin: ${miso_pin}
    interface: hardware

nrf24:
  id: my_nrf24
  spi_id: nrf24_spi
  cs_pin: ${cs_pin}
  ce_pin: ${ce_pin}
  channel: 53
  data_rate: 2MHz

directolor_radio:
  id: my_directolor_radio
  nrf24_id: my_nrf24
  directolor_code_attempts: ${payload_send_attempts}
  message_send_repeats: ${payload_send_repeats}

switch:
  - platform: template
    name: "Directolor Radio Listening"
    id: directolor_listening_switch
    optimistic: true                  
    restore_mode: RESTORE_DEFAULT_ON
    
    turn_on_action:
      - lambda: |-
          id(my_directolor_radio).set_listening(true);  # Call your component method
    
    turn_off_action:
      - lambda: |-
          id(my_directolor_radio).set_listening(false);
    
    lambda: |-
      return id(my_directolor_radio).is_listening();